### ISSUE TITLE
Segmentation fualt (again)

### ISSUE THREAD

**Issue by MichelNivard** [gkichaev/PAINTOR_V3.0#11]
I raised an issue regarding segmentation faults occuring before. THat turned out to be a case of specified paths. I am now again encountering segmentation faults, but at a later stage in the process. 

I run the following code:
./PAINTOR -input Data/input.files -out paintor_output/ -in Data/ -Zhead Zscore -LDname ld

Which sems to work becase POAINTOR starts reading files:
Reading in files for: ld_out.Ext1
Running PAINTOR in sampling mode. Parameters Used: 
Seed value: 1495436710
Number of draws for importance sampling: 1000000
Pre-computing functional enrichments considering up to 2 causals per locus
Segmentation fault (core dumped)

But again PAINTOR terminates after a segmentation fault.

All  LD and input files are created using the python tool provided with PAINTOR. I explicitly am trying to run PAINTOR without annotations, so perhaps that is causing the issue?

Best,
Michel

**Comment by gkichaev** [comment]
Hi Michel,

Since PAINTOR is intended to be used with annotations, it requires an annotation file as input. You can hack this by feeding it a dummy annotation file with all 1's. 

However, are you only interested in running PAINTOR without annotations? If so, I would recommend using the FINEMAP tool developed by Christian Benner:
http://www.christianbenner.com/#

I say this because you incur a statistical penalty (which could deflate performance) and computational overhead for estimating annotation enrichment parameters.

The inputs and outputs are more or less the same for both PAINTOR and FINEMAP.

**Comment by MichelNivard** [comment]
Hi,

I prefer to work in PAINTOR because we are still considering the inclusion of annotations (But are still working on a decision rule for including annotations if we decide to do so)

I do however encounter a new error.

When I run paintor for 1 lcus I get output and everything works great. When I then consider 42 loci I get the following error:

PAINTOR: /PAINTOR_V3.0/eigen/Eigen/src/Core/DenseCoeffsBase.h:378: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `index >= 0 && index < size()' failed.

Any syugestions what might be going on?

**Comment by MichelNivard** [comment]
I solved, it, for future reference this error arises if the dimensions of your annotations are not equal to the dimension of the other input files.

**Comment by erikstricker** [comment]
I wanted to just follow up that it happened when the annotation file was having all headers but not all columns filled. This happened to me when the annotation file directory of one of my files I use was wrong.
