### ISSUE TITLE
PAINTOR terminates after the first iteration

### ISSUE THREAD

**Issue by alessandrotestori** [gkichaev/PAINTOR_V3.0#6]
Hi. I am running PAINTOR with annotations. If I include all locus files I've generated for the input in this analysis in the "input.files" file I get the following error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  nlopt failure

and PAINTOR terminates after the first iteration.
I've tried to exclude the first half of these files and PAINTOR works fine; likewise, if I exclude the second half, PAINTOR terminates with no errors. I've checked my input files, but haven't found anything wrong with them. I've run PAINTOR with a different annotation and it works even if I include all files in the analysis. The only thing I've changed is the column with 0s and 1s; in both cases their sum is the same, of course. Any suggestions? Please let me know.

PS: I've found out it doesn't work if I run it on the only locus I have attached (version with annotations). However, if I change all 1s to 0s in the annotation file it works fine.

[Locus.29.tar.gz](https://github.com/gkichaev/PAINTOR_V3.0/files/827974/Locus.29.tar.gz)
[Locus.29.annotations.tar.gz](https://github.com/gkichaev/PAINTOR_V3.0/files/827978/Locus.29.annotations.tar.gz)
[Locus.29.ld.tar.gz](https://github.com/gkichaev/PAINTOR_V3.0/files/827980/Locus.29.ld.tar.gz)

**Comment by gkichaev** [comment]
Yes, the optimization is sometimes unstable for certain annotations. So far, I haven't come up with a way to fix this as it seems to fail randomly. From my experience it occurs when the annotations are relatively infrequent (i.e <5% of SNPs annotated). 

You can try Yue Li's fine mapping method:

https://github.com/yueli-compbio/RiVIERA-MT

It more or less the same thing as PAINTOR. The main difference is that it does MCMC instead of maximum likelihood to get the annotation enrichment parameters. 

Sorry that I don't have a more definitive answer. 

Good luck!
